namespace: lesson4356

image:
  repository: prom/prometheus
  tag: "latest"

replicaCount: 1

service:
  type: NodePort
  port: 9090
  targetPort: 9090
  nodePort: 30090

serviceAccount:
  name: prometheus

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"