auto_version: true
dockerfile_path: ../
dockerhub: null
helm_chart_path: ../../Helm/orders-service
helm_namespace: lesson4356
helm_release: orders-service
image: orders-service
registry: cr.yandex/crpiqtsurn6alildl4cb
tag: '2.14'
update_values: true
