apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
  namespace: lesson4356
type: Opaque
data:
  TEST_USER_PASSWORD: "cGFzc3dvcmQxMjM=" 
  TEST_USER_NAME: "Sm9obiBEb2U=" 
  TEST_USER_EMAIL: "dXNlckBleGFtcGxlLmNvbQ=="
