apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: lesson4356
data:
  ORDERS_SERVICE_URL: "http://orders-service:8002"
  POSTGRES_DB: "reviews"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  PORT: "8001"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
