apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lesson4356
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'reviews-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['reviews-service:8004']
        scrape_interval: 5s

      - job_name: 'users-service'
        metrics_path: /metrics  
        static_configs:
          - targets: ['users-service:8003']
        scrape_interval: 5s

      - job_name: 'orders-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['orders-service:8002']
        scrape_interval: 5s

      - job_name: 'products-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['products-service:8001']
        scrape_interval: 5s

      - job_name: 'frontend-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['frontend-service:80']
        scrape_interval: 5s  
          

      - job_name: 'kube-metrics'
        metrics_path: /metrics
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
        scrape_interval: 5s 


    rule_files:
      - "/etc/prometheus/rules/rules.yml"