image:
  repository: cr.yandex/crpiqtsurn6alildl4cb/frontend-service
  tag: '2.12'

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 15
  path: /health
  periodSeconds: 5
  port: 80
  timeoutSeconds: 2

namespace: lesson4356
prometheusScrape: false

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /health
  periodSeconds: 3
  port: 80
  timeoutSeconds: 2

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  nodePort: 30008
  port: 80
  targetPort: 80
  type: NodePort
