namespace: lesson4356
image:
  repository: cr.yandex/crpiqtsurn6alildl4cb/products-service
  tag: "2.13"


service:
  type: NodePort
  ports:
  port: 8001
  targetPort: 8001
  nodePort: 30001

ports:
- name: http-metrics      # ← Имя порта для ServiceMonitor
  port: 8001
  targetPort: 8001
  protocol: TCP
  nodePort: 30001

replicaCount: 1


config:
  ORDERS_SERVICE_URL: "http://orders-service-service:8002"
  PORT: "8001"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

secret:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "reviews"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "1000m"


livenessProbe:
  path: /live
  port: 8001
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /ready
  port: 8001
  initialDelaySeconds: 10
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3
  enabled: false
