apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}