namespace: lesson4356
image:
  repository: cr.yandex/crpiqtsurn6alildl4cb/orders-service
  tag: "2.14"

service:
  type: NodePort
  ports:
  port: 8002
  targetPort: 8002
  nodePort: 30002

ports:
- name: http-metrics      # ← Имя порта для ServiceMonitor
  port: 8002
  targetPort: 8002
  protocol: TCP
  nodePort: 30002

replicaCount: 1


config:
  PRODUCTS_SERVICE_URL: "http://products-service-service:8001"
  USERS_SERVICE_URL: "http://users-service-service:8003"
  PORT: "8002"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

secret:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "reviews"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

livenessProbe:
  path: /live
  port: 8002
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /ready
  port: 8002
  initialDelaySeconds: 10
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3
  enabled: false

