apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.serviceName }}-rollout
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  strategy:
    canary:
      steps:
        {{- toYaml .Values.strategy.canary.steps | nindent 8 }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.serviceName }}-config
            # TODO: раскомментировать после создания secret.yaml
            # - secretRef:
            #     name: {{ .Values.serviceName }}-secret

          # =================================================================
          # TODO: Добавить livenessProbe
          # =================================================================
          # {{- if .Values.livenessProbe }}
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.livenessProbe.path }}
          #     port: {{ .Values.livenessProbe.port }}
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          # {{- end }}

          # =================================================================
          # TODO: Добавить readinessProbe
          # =================================================================
          # {{- if .Values.readinessProbe }}
          # readinessProbe:
          #   httpGet:
          #     path: {{ .Values.readinessProbe.path }}
          #     port: {{ .Values.readinessProbe.port }}
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          # {{- end }}

          # =================================================================
          # TODO: Добавить resources
          # =================================================================
          # {{- if .Values.resources }}
          # resources:
          #   {{- toYaml .Values.resources | nindent 12 }}
          # {{- end }}
