apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.serviceName }}-rollout
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  strategy:
    canary:
      steps:
        {{- tpl (toYaml .Values.strategy.canary.steps) . | nindent 8 }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.serviceName }}-config
            {{- if .Values.secret }}
            - secretRef:
                name: {{ .Values.serviceName }}-secret
            {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            {{- if .Values.livenessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            {{- end }}
            {{- if .Values.livenessProbe.failureThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            {{- end }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            {{- if .Values.readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            {{- end }}
            {{- if .Values.readinessProbe.failureThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- end }}
          {{- end }}

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
    
            # TODO: раскомментировать после создания secret.yaml
            # - secretRef:
            #     name: {{ .Values.serviceName }}-secret

          # =================================================================
          # TODO: Добавить livenessProbe
          # =================================================================
          # {{- if .Values.livenessProbe }}
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.livenessProbe.path }}
          #     port: {{ .Values.livenessProbe.port }}
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          # {{- end }}

          # =================================================================
          # TODO: Добавить readinessProbe
          # =================================================================
          # {{- if .Values.readinessProbe }}
          # readinessProbe:
          #   httpGet:
          #     path: {{ .Values.readinessProbe.path }}
          #     port: {{ .Values.readinessProbe.port }}
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          # {{- end }}

          # =================================================================
          # TODO: Добавить resources
          # =================================================================
          # {{- if .Values.resources }}
          # resources:
          #   {{- toYaml .Values.resources | nindent 12 }}
          # {{- end }}
