auto_version: true
dockerfile_path: ../
dockerhub: null
helm_chart_path: ../../Helm/frontend-service
helm_namespace: lesson4356
helm_release: frontend-service
image: frontend-service
registry: cr.yandex/crpiqtsurn6alildl4cb
tag: '2.12'
update_values: true
