{
 "title": "Бизнес метрики",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servise", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate логинов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(user_logins_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu_limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "app_cpu_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Товары с низким остатком",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "count(products_stock_total < 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "memory_limit_mib",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "app_memory_limit_mib{job=~\"$servise\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Выручка по часам (для выявления пиков)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "sum by (hour) (rate(revenue_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu_usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "targets": [
    { "expr": "app_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "memory_usage_mib",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 16 },
   "targets": [
    { "expr": "app_memory_usage_mib", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Новые пользователи за день",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "increase(users_registered_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логауты за минуту",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "targets": [
    { "expr": "rate(user_logouts_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Топ-10 самых продаваемых товаров",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (product_id, product_name) (\n    rate(order_items_total[24h])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Новые регистрации за минуту",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "rate(users_registered_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GMV (Gross Merchandise Volume)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "targets": [
    { "expr": "increase(revenue_total[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Выручка за последние 24 часа",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 29 },
   "targets": [
    { "expr": "increase(revenue_total[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество HTTP запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}