{
 "title": "Ресурсные метрики",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "servise", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory Resources: Usage, Requests & Limits",
   "type": "barchart",
   "description": "График показывает полную картину использования памяти приложением, сравнивая фактическое потребление с зарезервированными (requests) и максимальными (limits) ресурсами, что позволяет анализировать эффективность выделения памяти и выявлять риски нехватки или перерасхода.\n\n- Оптимизация ресурсов и снижение costs\n- Предотвращение OOMKilled инцидентов\n- Планирование масштабирования на основе реального использования\n\nИтог: График обеспечивает полный контроль над использованием памяти, помогая балансировать между стабильностью работы приложения и эффективным использованием ресурсов кластера.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{container=~\"$servise\", resource=\"memory\"}/ 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{container=~\"$servise\", resource=\"memory\"}/ 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "app_memory_usage_mib{job=~\"$servise\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limits: Kubernetes vs Application",
   "type": "stat",
   "description": "График сравнивает ограничения памяти на двух уровнях инфраструктуры: установленные в Kubernetes (контейнерные limits) и заявленные самим приложением (application-level limits), что позволяет выявить расхождения в конфигурации и обеспечить согласованность ограничений для предотвращения OOM-ситуаций.\n\n- Валидация конфигурации при развертывании\n- Обнаружение дрифта настроек между средами\n- Предотвращение OOMKilled через согласование лимитов\n- Оптимизация ресурсов для cost-efficiency\n\nИтог: График обеспечивает видимость согласованности memory ограничений на разных уровнях стека, помогая предотвратить OOM-инциденты и оптимизировать использование ресурсов кластера.",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{container=~\"$servise\", resource=\"memory\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Memory Usage",
   "type": "gauge",
   "description": "Фактическое использование оперативной памяти процессом приложения в мебибайтах\n\n- Реальный объем RAM, используемый процессом приложения\n- Потребление памяти на уровне приложения, а не контейнера или ноды\n- Текущую нагрузку в мебибайтах (MiB)\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_memory_usage_mib{job=~\"$servise\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU: Requested / Limit",
   "type": "barchart",
   "description": "График показывает распределение CPU ресурсов между зарезервированными (requests), ограничивающими (limits) и фактически используемыми ресурсами, что позволяет анализировать эффективность выделения ресурсов и выявлять дисбалансы.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{container=~\"$servise\", resource=\"cpu\"}*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{container=~\"$servise\", resource=\"cpu\"}*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "app_cpu_usage_percent{job=~\"$servise\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limits: Kubernetes vs Application",
   "type": "stat",
   "description": "График сравнивает ограничения CPU ресурсов на двух уровнях: установленные в Kubernetes (контейнерные limits) и заявленные самим приложением (application-level limits), что позволяет выявить расхождения в конфигурации и обеспечить согласованность ограничений.",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{container=~\"$servise\", resource=\"cpu\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application CPU Usage",
   "type": "gauge",
   "description": "Процент использования CPU процессом приложения\n\nЧто измеряет метрика:\n\n- Фактическое использование CPU самим приложением (процессом)\n- Процент от одного CPU ядра (100% = 1 полное ядро)\n- Нагрузку на процессор на уровне приложения, а не контейнера",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_cpu_usage_percent{job=~\"$servise\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Performance Monitoring",
   "type": "timeseries",
   "description": "Этот график показывает время обработки запросов по разным перцентилям и категориям ответов, что позволяет анализировать производительность и выявлять аномалии.\n\n- Время ответа сервисов \n- Процент ошибок\n- Активные соединения\n- Скорость переполнения соединений",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(istio_request_duration_milliseconds_bucket{destination_app=~\"$servise\"}[5m])) by (le, destination_service)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(istio_request_duration_milliseconds_bucket{destination_app=~\"$servise\"}[5m])) by (le, destination_service)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..\",destination_app=~\"$servise\"}[5m])) by (le, destination_service)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"4..|5..\",destination_app=~\"$servise\"}[5m])) by (le, destination_service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Service and Status Code",
   "type": "timeseries",
   "description": "Этот график показывает интенсивность HTTP-трафика с детализацией по сервисам и статус-кодам ответов, что позволяет анализировать нагрузку и распределение типов ответов в реальном времени\n\nНагрузочный анализ:\n\n- Пиковые нагрузки - максимальное количество запросов в секунду\n- Распределение трафика - какие сервисы наиболее нагружены\n- Суточные паттерны - циклические изменения нагрузки\n\nАнализ качества:\n\n- Соотношение успешных/ошибочных запросов\n- Динамика ошибок - рост 4xx/5xx ответов\n- Эффективность редиректов - количество 3xx ответов",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_app=~\"$servise\"}[5m])) by (response_code, destination_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Request Rate",
   "type": "timeseries",
   "description": "Количество ошибочных HTTP запросов в секунду (4xx и 5xx) по сервисам",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"5..\", destination_app=~\"$servise\"}[5m])) by (response_code, destination_app)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"4..\", destination_app=~\"$servise\"}[5m])) by (response_code, destination_app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (95th/99th percentile)",
   "type": "timeseries",
   "description": "Время обработки запросов для 95% и 99% трафика\n- 95th percentile - 95% запросов обрабатываются быстрее этого времени\n- 99th percentile - 99% запросов обрабатываются быстрее этого времени\n- Оставшиеся 1-5% - самые медленные запросы (выбросы)\n",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(istio_request_duration_milliseconds_bucket{destination_app=~\"$servise\"}[5m])) by (le, destination_service)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(istio_request_duration_milliseconds_bucket{destination_app=~\"$servise\"}[5m])) by (le, destination_service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Data Rate",
   "type": "piechart",
   "description": "Скорость получения входящих данных в байтах в секунду\n- Объем данных получаемых сервисом в единицу времени\n- Нагрузку на сетевой интерфейс от входящих запросов\n- Интенсивность передачи данных к сервису",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(istio_request_bytes_sum{destination_app=~\"$servise\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(istio_response_bytes_sum{destination_app=~\"$servise\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "description": "Процент ошибочных HTTP ответов (4xx и 5xx коды)\n- Процент запросов завершившихся с ошибками\n- 4xx коды - клиентские ошибки (400, 404, 429 и т.д.)\n- 5xx коды - серверные ошибки (500, 502, 503 и т.д.)\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(istio_requests_total{response_code=~\"4..|5..\", destination_app=~\"$servise\"}[5m])) by (destination_app)\n  /\n  sum(rate(istio_requests_total{destination_app=~\"$servise\"}[5m])) by (destination_app)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Overflow Rate",
   "type": "timeseries",
   "description": "- Скорость превышения лимита соединений к upstream сервисам\n- Количество отказов при создании новых соединений из-за переполнения пула\n- Признак нехватки соединений в connection pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_overflow{app=~\"$servise\"}[5m])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "- Количество активных upstream соединений к кластеру\n- Активные TCP/HTTP соединения от Envoy к upstream сервисам\n- Размер connection pool в реальном времени\n- Нагрузка на сетевые соединения",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{app=~\"$servise\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(envoy_cluster_circuit_breakers_default_remaining_cx / \n(envoy_cluster_circuit_breakers_default_remaining_cx + \nenvoy_cluster_upstream_cx_active)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "stat",
   "description": " Процент использования оперативной памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "stat",
   "description": "Процент использования процессора за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (GB)",
   "type": "stat",
   "description": "Использованная оперативная память в гигабайтах",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inodes Usage (%)",
   "type": "stat",
   "description": "Метрика показывает процент использования inodes (инодов) файловой системы. Inodes - это структуры данных, которые хранят метаинформацию о файлах (права доступа, владелец, временные метки), при этом каждый файл или директория занимает ровно один inode.\n\n- ✅ 0.1-10% - Нормальное состояние, файловые системы не перегружены\n- ⚠️ 10-80% - Умеренная нагрузка, требует наблюдения\n- 🚨 80-90% - Высокая нагрузка, риск исчерпания inodes\n- 🔥 90-100% - Критическое состояние, невозможно создавать новые файлы",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_files_free{fstype=~\"ext4|xfs|btrfs\"} / node_filesystem_files{fstype=~\"ext4|xfs|btrfs\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "description": "Фактически использованное дисковое пространство на основных файловых системах в гигабайтах\n\nЧто измеряет метрика:\n\n- Объем данных занимаемый на диске в GB\n- Фактическое использование пространства (не включая свободное место)\n- Только основные файловые системы: корневая (/), системные (/var, /var/lib), пользовательские (/home)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  node_filesystem_size_bytes{mountpoint=~\"/|/var|/var/lib|/home\"} \n  - node_filesystem_avail_bytes{mountpoint=~\"/|/var|/var/lib|/home\"}\n) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "stat",
   "description": "Load Average (средняя нагрузка) показывает количество процессов в состоянии выполнения или ожидания ресурсов за последние 1, 5 и 15 минут. Это ключевой показатель общей загрузки системы.\n\n- 1.0 на 1 ядро - Низкая нагрузка ✅\n- 1.0-2.0 на 1 ядро - Нормальная нагрузка ⚠️\n- 2.0 на 1 ядро - Высокая нагрузка 🚨\n- 4.0 на 1 ядро - Критическая нагрузка 🔥",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  }
 ]
}