apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-config
  namespace: lesson4356
data:
  USERS_SERVICE_URL: "http://users-service:8003"
  PRODUCTS_SERVICE_URL: "http://products-service:8001"
  ORDERS_SERVICE_URL: "http://orders-service:8002"
  PORT: "8003"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
