apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service-deployment
  namespace: lesson4356
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
      - name: reviews-service
        image: reviews-service:1.0
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: reviews-config
        volumeMounts:
            - name: reviews-storage
              mountPath: /app/uploads
      volumes:
        - name: reviews-storage
          persistentVolumeClaim:
            claimName: reviews-pvc      

---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: lesson4356
spec:
  selector:
    app: reviews-service
  type: NodePort
  ports:
    - port      : 8003         # Порт сервиса внутри кластера
      targetPort: 8003         # Порт внутри контейнера
      nodePort  : 30005        # Порт наружу