apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service-deployment
  namespace: lesson4356
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
      - name: reviews-service
        image: reviews-service:8.0
        ports:
        - containerPort: 8004
        envFrom:
          - configMapRef:
              name: reviews-config
          - secretRef:
              name: reviews-secret
        volumeMounts:
          - name: reviews-storage
            mountPath: /app/uploads
        livenessProbe:
          httpGet:
            path: /live
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8004
        #   initialDelaySeconds: 10
        #   periodSeconds: 3
        #   timeoutSeconds: 2
        #   failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
        - name: reviews-storage
          persistentVolumeClaim:
            claimName: reviews-pvc      

---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: lesson4356
spec:
  selector:
    app: reviews-service
  type: NodePort
  ports:
    - port      : 8004         # Порт сервиса внутри кластера
      targetPort: 8004         # Порт внутри контейнера
      nodePort  : 30009        # Порт наружу