apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-deployment
  namespace: lesson4356
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: frontend-service:2.0    
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 3       
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lesson4356
spec:
  selector:
    app: frontend-service
  type: NodePort
  ports:
    - port      : 80         # Порт сервиса внутри кластера
      targetPort: 80         # Порт внутри контейнера
      nodePort  : 30008        # Порт наружу