user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Логирование
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/products/ {
            proxy_pass http://products-service:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            proxy_pass http://orders-service:8002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/users/ {
            proxy_pass http://users-service:8003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/reviews/ {
            proxy_pass http://reviews-service:8004/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        types {
            text/html html htm;
            text/css css;
            application/javascript js;
            image/jpeg jpg jpeg;
            image/png png;
        }
    }
}